// <auto-generated />
using System;
using CoupleApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoupleApp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412121800_AddDrawGameEntities")]
    partial class AddDrawGameEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoupleApp.Core.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.CoupleInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InviterUserId");

                    b.ToTable("CoupleInvitations");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.CouplePair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PairedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("User1Id")
                        .IsUnique();

                    b.HasIndex("User2Id")
                        .IsUnique();

                    b.ToTable("CouplePairs");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.DrawSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrawerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuesserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DrawerId");

                    b.HasIndex("GuesserId");

                    b.ToTable("DrawSessions");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.DrawWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DrawWords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Category = "Yiyecek",
                            Difficulty = 0,
                            Word = "Elma"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000002"),
                            Category = "Hayvan",
                            Difficulty = 0,
                            Word = "Kedi"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000003"),
                            Category = "Hayvan",
                            Difficulty = 0,
                            Word = "Köpek"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000004"),
                            Category = "Doğa",
                            Difficulty = 0,
                            Word = "Güneş"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000005"),
                            Category = "Yapılar",
                            Difficulty = 0,
                            Word = "Ev"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000006"),
                            Category = "Araçlar",
                            Difficulty = 0,
                            Word = "Araba"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000007"),
                            Category = "Yiyecek",
                            Difficulty = 0,
                            Word = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000008"),
                            Category = "Doğa",
                            Difficulty = 0,
                            Word = "Çiçek"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000009"),
                            Category = "Araçlar",
                            Difficulty = 1,
                            Word = "Uçak"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000010"),
                            Category = "Fantastik",
                            Difficulty = 1,
                            Word = "Ejderha"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000011"),
                            Category = "Meslekler",
                            Difficulty = 1,
                            Word = "Astronot"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000012"),
                            Category = "Eylemler",
                            Difficulty = 1,
                            Word = "Fısıldamak"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000013"),
                            Category = "Doğa",
                            Difficulty = 1,
                            Word = "Yıldırım"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000014"),
                            Category = "Kavramlar",
                            Difficulty = 2,
                            Word = "Özgürlük"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000015"),
                            Category = "Duygular",
                            Difficulty = 2,
                            Word = "Kıskançlık"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000016"),
                            Category = "Kavramlar",
                            Difficulty = 2,
                            Word = "Karantina"
                        });
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.GalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaIdForReceiver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaIdForSender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("UploaderId");

                    b.ToTable("GalleryItems");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.GameTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("GameTasks");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTextForSender")
                        .HasColumnType("text");

                    b.Property<string>("IV")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.Activity", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "CreatedBy")
                        .WithMany("Activities")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.CoupleInvitation", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.CouplePair", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleApp.Core.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.DeviceToken", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.DrawSession", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "Drawer")
                        .WithMany()
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleApp.Core.Entities.User", "Guesser")
                        .WithMany()
                        .HasForeignKey("GuesserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drawer");

                    b.Navigation("Guesser");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.GalleryItem", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleApp.Core.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.GameTask", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleApp.Core.Entities.User", "AssignedTo")
                        .WithMany("GameTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.Message", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleApp.Core.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CoupleApp.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoupleApp.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("DeviceTokens");

                    b.Navigation("GameTasks");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
